apiVersion: apps/v1
kind: Deployment
metadata:
  name: greyscale
spec:
  selector:
    matchLabels:
      app: greyscale
  template:
    metadata:
      labels:
        app: greyscale
    spec:
      containers:
      - name: greyscale
        image: oriree70/greyscale:1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: greyscale
spec:
  type: LoadBalancer
  selector:
    app: greyscale
  ports:
  - port: 80
    targetPort: 80
